baseURL = "https://ounose.noor.jp/"
languageCode = "ja"
title = "衛星のポライトネス"
theme = "random3"

paginate = 5

[params]
  description = "30代、乳がん再発予防治療をしながらの生活と読書日記"
  author = "Ukai"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  noClasses = false

[taxonomies]
  tag = "tags"
  category = "categories"